"""Base class for Polymarket trading strategies."""

from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Optional


@dataclass
class TradeSignal:
    """A single trade recommendation generated by a strategy."""
    market_question: str
    market_slug: str
    condition_id: str
    token_id: str
    side: str                    # "BUY" or "SELL"
    outcome: str                 # "Yes" or "No"
    price: float                 # limit price
    size: int                    # number of tokens
    expected_value: float        # expected value per token
    confidence: float            # 0-1
    strategy: str               # strategy name
    reason: str                 # human-readable explanation
    generated_at: str = field(default_factory=lambda: datetime.utcnow().isoformat())


class StrategyResult:
    """Result from a strategy run."""
    def __init__(self, signals: list[TradeSignal], metadata: Optional[dict] = None):
        self.signals = signals
        self.metadata = metadata or {}
        self.timestamp = datetime.utcnow()

    @property
    def total_signals(self) -> int:
        return len(self.signals)

    @property
    def high_confidence(self) -> list[TradeSignal]:
        return [s for s in self.signals if s.confidence >= 0.8]

    def __bool__(self) -> bool:
        return len(self.signals) > 0


class BaseStrategy(ABC):
    """Base strategy interface.

    Subclasses implement ``run()`` which returns a ``StrategyResult``
    containing trade signals.
    """

    def __init__(self, name: str):
        self.name = name

    @abstractmethod
    def run(self, markets: list[Any]) -> StrategyResult:
        """Analyse markets and return trade signals."""
        ...

    def __repr__(self) -> str:
        return f"<{self.__class__.__name__}: {self.name}>"
